'use strict';

//import src\js\webgl\macros.js
//import src\js\webgl\math.js
//import src\js\webgl\stack.js
//import src\js\webgl\time.js
//import src\js\webgl\vector.js
//import src\js\webgl\quaternion.js
//import src\js\webgl\mat3.js
//import src\js\webgl\mat4.js
//import src\js\webgl\curve.js
//import src\js\webgl\random.js
//import src\js\webgl\projection.js
//import src\js\webgl\intersect.js
//import src\js\webgl\serialise.js
//import src\js\webgl\assets.js
//import src\js\webgl\shader.js
//import src\js\webgl\texture.js
//import src\js\webgl\image.js
//import src\js\webgl\mesh.js
//import src\js\webgl\font.js
//import src\js\webgl\text.js
//import src\js\webgl\webgl.js
//import src\js\webgl\rig.js
//import src\js\webgl\animation.js
//import src\js\webgl\entity.js
//import src\js\webgl\camera.js
//import src\js\webgl\input.js
//import src\js\webgl\quad.js
//import src\js\webgl\fly_cam.js
//import src\js\webgl\gl_draw.js
